# Generated by Django 4.1.7 on 2023-03-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_transaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('USD', '€')], default='USD', max_length=8),
        ),
    ]
